/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Modelos.Saude;
import SQL.SaudeDAO;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Cabessa
 */
public class IMC extends javax.swing.JDialog {

    /**
     * Creates new form IMC
     */
    float MinhAltura,MePeso,Resultado;
    int pontoAltura = 0;
    int pontoPeso = 0;
    public IMC(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtAltura = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelIMC = new javax.swing.JLabel();
        labelSituacao = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calcular IMC");
        setIconImage(new ImageIcon(getClass().getResource("/imagens/icon.png")).getImage());
        setResizable(false);
        getContentPane().setLayout(null);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelar.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.setToolTipText("Sair do Programa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 170, 138, 30);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/limpar.png"))); // NOI18N
        jButton3.setText("Limpar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(220, 110, 138, 30);

        jButton1.setText("Calcular");
        jButton1.setToolTipText("Clicar depois de inserir os dados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 50, 138, 30);

        txtAltura.setToolTipText("Digite sua altura (Ex: 1.70)");
        txtAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlturaActionPerformed(evt);
            }
        });
        txtAltura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAlturaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAlturaKeyTyped(evt);
            }
        });
        getContentPane().add(txtAltura);
        txtAltura.setBounds(90, 80, 80, 30);

        txtPeso.setToolTipText("Digite aqui seu peso (Ex: 70)");
        txtPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPesoKeyTyped(evt);
            }
        });
        getContentPane().add(txtPeso);
        txtPeso.setBounds(90, 120, 80, 30);

        jLabel2.setText("Seu Peso:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 120, 70, 30);

        jLabel1.setText("Sua Altura:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 80, 80, 30);

        labelIMC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelIMC.setForeground(new java.awt.Color(0, 51, 255));
        labelIMC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIMC.setToolTipText("Seu IMC");
        labelIMC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(labelIMC);
        labelIMC.setBounds(20, 230, 340, 62);

        labelSituacao.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelSituacao.setForeground(new java.awt.Color(0, 204, 51));
        labelSituacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSituacao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(labelSituacao);
        labelSituacao.setBounds(20, 320, 340, 67);

        jLabel3.setText("SEU IMC:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 210, 70, 14);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Índice de massa corporal");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 10, 240, 30);

        btnRegistrar.setText("Registrar");
        btnRegistrar.setEnabled(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar);
        btnRegistrar.setBounds(140, 410, 100, 30);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 390, 460);

        setBounds(0, 0, 396, 487);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // ESTE CÓDIGO AQUI CALCULA O IMC
        pontoAltura = 0;
        pontoPeso = 0;
        if(txtAltura.getText().isEmpty() || txtPeso.getText().isEmpty())
        {       
            JOptionPane.showMessageDialog(null, "Informe os valores a serem calculados!");
        }else
        {
        btnRegistrar.setEnabled(true);
        MinhAltura = Float.valueOf(txtAltura.getText());
        MePeso = Float.valueOf(txtPeso.getText());
        Resultado = MePeso / (MinhAltura * MinhAltura);
        labelIMC.setText(String.valueOf(Resultado));

        if (Resultado <= 18.5){
            labelSituacao.setText(String.valueOf("ABAIXO DO PESO"));
        }
        if (Resultado > 30 && Resultado <=34.9 ){
            labelSituacao.setText(String.valueOf("OBESIDADE TIPO 1"));
        }
        if (Resultado > 18.6 && Resultado <=24.9 ){
            labelSituacao.setText(String.valueOf("PESO NORMAL"));
        }
        if (Resultado > 25 && Resultado <=29.9 ){
            labelSituacao.setText(String.valueOf("SOBRE PESO"));
        }
        if (Resultado > 30 && Resultado <=34.9 ){
            labelSituacao.setText(String.valueOf("OBESIDADE TIPO 1"));
        }
        if (Resultado > 35 && Resultado <=39.9 ){
            labelSituacao.setText(String.valueOf("OBESIDADE TIPO 2"));
        }
        if (Resultado > 40){
            labelSituacao.setText(String.valueOf("OBESIDADE MÓRBIDA"));
        }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // ESTE CÓDIGO ABAIXO SAI DA APLICAÇAO:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        txtPeso.setText("");
        txtAltura.setText("");
        labelIMC.setText(null);
        labelSituacao.setText(null);
        btnRegistrar.setEnabled(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlturaActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
       if( (txtAltura.getText().isEmpty()) || (txtPeso.getText().isEmpty()) )
        {
            JOptionPane.showMessageDialog(null, "Por favor preecha todos os campos!");
        }
        else if ( Double.parseDouble(txtAltura.getText())  > 4 || Double.parseDouble(txtAltura.getText()) < 0.1 )
        {
            JOptionPane.showMessageDialog(null, "Altura Inválida");
        }
        else if( Double.parseDouble(txtPeso.getText()) > 300 ||  Double.parseDouble(txtPeso.getText()) < 0)
        {
            JOptionPane.showMessageDialog(null, "Peso Inválido");
        }
        else
        {
            Saude saude = new Saude();
            saude.setAltura(Double.parseDouble(txtAltura.getText()));
            saude.setPeso(Double.parseDouble(txtPeso.getText()));
            saude.setImc(saude.getPeso() / (Math.pow(saude.getAltura(), 2)));
            saude.setSituacao(labelSituacao.getText());

            SaudeDAO dao = new SaudeDAO();
            dao.adicionarSaude(saude);

            dao.getSaude();
            dispose();
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtAlturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlturaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_PERIOD) 
    {  
        pontoAltura++;
        if(pontoAltura > 1)
        {
        JOptionPane.showMessageDialog(null, "Sua altura não pode conter dois pontos.");
        pontoAltura = 0;
        
        String caracteres="098765432.1";
        if(!caracteres.contains(evt.getKeyChar()+""))
        {
        evt.consume();
        }
         
        txtAltura.setText("");
        }
    } 
    }//GEN-LAST:event_txtAlturaKeyPressed

    private void txtPesoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesoKeyPressed
            if (evt.getKeyCode() == KeyEvent.VK_PERIOD) 
    {  
        pontoPeso++;
        if(pontoPeso > 1)
        {
        JOptionPane.showMessageDialog(null, "Seu peso não pode conter dois pontos.");
        pontoPeso = 0;
        
        String caracteres="098765432.1";
        if(!caracteres.contains(evt.getKeyChar()+""))
        {
        evt.consume();
        }
         
        txtPeso.setText("");
        }
    } 
    }//GEN-LAST:event_txtPesoKeyPressed

    private void txtPesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesoKeyTyped
        String caracteres="0987654321.";
        if(!caracteres.contains(evt.getKeyChar()+""))
        {
        evt.consume();
        }  
    }//GEN-LAST:event_txtPesoKeyTyped

    private void txtAlturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlturaKeyTyped
        String caracteres="0987654321.";
        if(!caracteres.contains(evt.getKeyChar()+""))
        {
        evt.consume();
        }  
    }//GEN-LAST:event_txtAlturaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IMC dialog = new IMC(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelIMC;
    private javax.swing.JLabel labelSituacao;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
