/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import SQL.BoletimDAO;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Cabessa i5
 */
public class MeuBoletim extends javax.swing.JDialog {

    static String linhaBoletim = "0";
    static String linhaNotas = "0";
    public MeuBoletim(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();
    }
    
    
    public void deletaBoletim()
    {
        
        if ("0".equals(linhaBoletim))
        {
            JOptionPane.showMessageDialog(null,"Ecolha um boletim para excluir");
        }
        else 
        {
            BoletimDAO boletimDAO = new BoletimDAO();
            boletimDAO.deletarBoletim(linhaBoletim);
            linhaBoletim = "0";
            boletimDAO.getBoletim();
        }
    }
    
    public void deletaDisciplina()
    {
        
        if ("0".equals(linhaNotas))
        {
            JOptionPane.showMessageDialog(null,"Ecolha uma disciplina para excluir");
        }
        else 
        {
            BoletimDAO boletim = new BoletimDAO();
            boletim.deletarDisciplina(linhaNotas);
            linhaNotas = "0";
            boletim.getDisciplina(linhaBoletim);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBoletim = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableNotas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Meu Boletim");
        setIconImage(new ImageIcon(getClass().getResource("/imagens/icon.png")).getImage());
        setResizable(false);
        getContentPane().setLayout(null);

        jTableBoletim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableBoletim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBoletimMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableBoletimMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableBoletimMouseReleased(evt);
            }
        });
        jTableBoletim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableBoletimKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableBoletim);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 80, 560, 330);

        jButton3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/adicionar.png"))); // NOI18N
        jButton3.setText("Adicionar disciplina");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(680, 430, 180, 40);

        jButton4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelar.png"))); // NOI18N
        jButton4.setText("Apagar disciplina");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(1070, 430, 170, 40);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel1.setText("Notas relacionadas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(840, 20, 290, 60);

        jButton5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar.png"))); // NOI18N
        jButton5.setText("Editar disciplina");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(870, 430, 190, 40);

        jButton6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelar.png"))); // NOI18N
        jButton6.setText("Apagar boletim");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(430, 430, 170, 40);

        jButton7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar.png"))); // NOI18N
        jButton7.setText("Editar boletim");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(230, 430, 190, 40);

        jButton8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/adicionar.png"))); // NOI18N
        jButton8.setText("Adicionar boletim");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(40, 430, 180, 40);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(640, 80, 20, 390);

        jTableNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableNotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableNotasMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableNotasMousePressed(evt);
            }
        });
        jTableNotas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableNotasKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTableNotasKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jTableNotas);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(680, 80, 560, 330);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel2.setText("Boletins");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 10, 170, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/boletimNovo.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1200, 0, 70, 80);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bg.jpg"))); // NOI18N
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1290, 540);

        setSize(new java.awt.Dimension(1289, 559));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableBoletimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBoletimMouseClicked
        int linha_selecionada = jTableBoletim.getSelectedRow();
        linhaBoletim = (String.valueOf(jTableBoletim.getValueAt(linha_selecionada, 0)));
        
        BoletimDAO boletim = new BoletimDAO();
        boletim.getDisciplina(linhaBoletim);
    }//GEN-LAST:event_jTableBoletimMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        JFrame mainFrame = new JFrame();
        AdicionarDisciplina adicionar = new AdicionarDisciplina(mainFrame, true);
        adicionar.setLocationRelativeTo(mainFrame);
        adicionar.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        deletaDisciplina();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if ("0".equals(linhaBoletim))
        {
            JOptionPane.showMessageDialog(null, "Ecolha uma disciplina para editar!");
        }
        else
        {        
        JFrame mainFrame = new JFrame();
        AlterarDisciplina boletim = new AlterarDisciplina(mainFrame, true);
        boletim.setLocationRelativeTo(mainFrame);
        boletim.setVisible(true);                  
        
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        deletaBoletim();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if ("0".equals(linhaBoletim))
        {
            JOptionPane.showMessageDialog(null, "Ecolha um boletim para editar!");
        }
        else
        {        
        JFrame mainFrame = new JFrame();
        AlterarBoletim boletim = new AlterarBoletim(mainFrame, true);
        boletim.setLocationRelativeTo(mainFrame);
        boletim.setVisible(true);                  
        
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        JFrame mainFrame = new JFrame();
        AdicionarBoletim adicionar = new AdicionarBoletim(mainFrame, true);
        adicionar.setLocationRelativeTo(mainFrame);
        adicionar.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTableBoletimMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBoletimMouseReleased
      int linha_selecionada = jTableBoletim.getSelectedRow();
        linhaBoletim = (String.valueOf(jTableBoletim.getValueAt(linha_selecionada, 0)));
        
        BoletimDAO boletim = new BoletimDAO();
        boletim.getDisciplina(linhaBoletim);  
    }//GEN-LAST:event_jTableBoletimMouseReleased

    private void jTableNotasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableNotasKeyTyped
        
        
    }//GEN-LAST:event_jTableNotasKeyTyped

    private void jTableNotasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableNotasMouseClicked
        int linha_selecionada = jTableNotas.getSelectedRow();
        linhaNotas = (String.valueOf(jTableNotas.getValueAt(linha_selecionada, 0)));
    }//GEN-LAST:event_jTableNotasMouseClicked

    private void jTableBoletimKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableBoletimKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) 
        {
        BoletimDAO boletim = new BoletimDAO();      
        boletim.deletarBoletim(linhaBoletim);     
        linhaBoletim = "0"; 
        boletim.getBoletim();  
        }
    }//GEN-LAST:event_jTableBoletimKeyPressed

    private void jTableNotasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableNotasKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) 
        {
        BoletimDAO boletim = new BoletimDAO();      
        boletim.deletarDisciplina(linhaNotas);     
        linhaNotas = "0"; 
        boletim.getDisciplina(linhaBoletim);  
        }
    }//GEN-LAST:event_jTableNotasKeyPressed

    private void jTableBoletimMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBoletimMousePressed
        int linha_selecionada = jTableBoletim.getSelectedRow();
        linhaBoletim = (String.valueOf(jTableBoletim.getValueAt(linha_selecionada, 0)));
        
        BoletimDAO boletim = new BoletimDAO();
        boletim.getDisciplina(linhaBoletim);
    }//GEN-LAST:event_jTableBoletimMousePressed

    private void jTableNotasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableNotasMousePressed
        int linha_selecionada = jTableNotas.getSelectedRow();
        linhaNotas = (String.valueOf(jTableNotas.getValueAt(linha_selecionada, 0)));
    }//GEN-LAST:event_jTableNotasMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeuBoletim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeuBoletim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeuBoletim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeuBoletim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MeuBoletim dialog = new MeuBoletim(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTable jTableBoletim;
    public static javax.swing.JTable jTableNotas;
    // End of variables declaration//GEN-END:variables
}
