/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import SQL.SaudeDAO;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Cabessa i5
 */
public class MinhaSaude extends javax.swing.JDialog {

    /**
     * Creates new form MinhaSaude
     */
    String linhaSaude = "0";
    public MinhaSaude(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();
    }
        
    public void deletaSaude()
    {
        if ("0".equals(linhaSaude))
        {
            JOptionPane.showMessageDialog(null,"Ecolha um registro para excluir");
        }
        else 
        {
            SaudeDAO saude = new SaudeDAO();      
            saude.deletarSaude(linhaSaude);
            linhaSaude = "0";            
            saude.getSaude();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSaude = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Minha Saúde");
        setIconImage(new ImageIcon(getClass().getResource("/imagens/icon.png")).getImage());
        setResizable(false);
        getContentPane().setLayout(null);

        Titulo1.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        Titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo1.setText("Histórico de Saúde");
        getContentPane().add(Titulo1);
        Titulo1.setBounds(170, 20, 265, 50);

        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/adicionar.png"))); // NOI18N
        jButton1.setText("Calcular IMC");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 380, 150, 40);

        jButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelar.png"))); // NOI18N
        jButton2.setText("Excluir registro");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(310, 380, 150, 40);

        jTableSaude.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableSaude.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSaudeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableSaudeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableSaudeMouseReleased(evt);
            }
        });
        jTableSaude.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableSaudeKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSaude);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 80, 450, 280);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/saudeNovo.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(510, 0, 80, 80);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/saude.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 460);

        setSize(new java.awt.Dimension(599, 488));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFrame mainFrame = new JFrame();
        IMC saude = new IMC(mainFrame, true);
        saude.setLocationRelativeTo(mainFrame);
        saude.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        deletaSaude();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTableSaudeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSaudeMouseClicked
        int linha_selecionada = jTableSaude.getSelectedRow();
        linhaSaude =(String.valueOf(jTableSaude.getValueAt(linha_selecionada, 0)));
    }//GEN-LAST:event_jTableSaudeMouseClicked

    private void jTableSaudeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableSaudeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) 
        {
        SaudeDAO saude = new SaudeDAO();      
        saude.deletarSaude(linhaSaude);     
        linhaSaude = "0"; 
        saude.getSaude();  
        }
    }//GEN-LAST:event_jTableSaudeKeyPressed

    private void jTableSaudeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSaudeMouseReleased
        int linha_selecionada = jTableSaude.getSelectedRow();
        linhaSaude =(String.valueOf(jTableSaude.getValueAt(linha_selecionada, 0)));
    }//GEN-LAST:event_jTableSaudeMouseReleased

    private void jTableSaudeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSaudeMousePressed
        int linha_selecionada = jTableSaude.getSelectedRow();
        linhaSaude =(String.valueOf(jTableSaude.getValueAt(linha_selecionada, 0)));
    }//GEN-LAST:event_jTableSaudeMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MinhaSaude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MinhaSaude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MinhaSaude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MinhaSaude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MinhaSaude dialog = new MinhaSaude(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTableSaude;
    // End of variables declaration//GEN-END:variables
}
